export const POKEMONES_GET_SOLICITUD = 'POKEMONES_GET_SOLICITUD';
export const POKEMONES_GET_EJECUCION = 'POKEMONES_GET_EJECUCION';
export const POKEMONES_GET_RESPONSE  = 'POKEMONES_GET_RESPONSE';

export const POKEMONES_FIND_SOLICITUD = 'POKEMONES_FIND_SOLICITUD';
export const POKEMONES_FIND_EJECUCION = 'POKEMONES_FIND_EJECUCION';
export const POKEMONES_FIND_RESPONSE  = 'POKEMONES_FIND_RESPONSE';
export const POKEMONES_FIND_VOID  = 'POKEMONES_FIND_VOID';

export const POKEMONES_DELETE_SOLICITUD = 'POKEMONES_DELETE_SOLICITUD';
export const POKEMONES_DELETE_EJECUCION = 'POKEMONES_DELETE_EJECUCION';
export const POKEMONES_DELETE_RESPONSE  = 'POKEMONES_DELETE_RESPONSE';